config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rjdmartins/try_ibergrid2022_sqaaas:
      branch: master
      repo: https://github.com/rjdmartins/try_ibergrid2022_sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-bistre-bear.sh
        container: qc.acc_snazzy-denim-hedgehog
  QC.Doc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-plum-orangutan.sh
        container: qc.doc_crabby-silver-eel
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-brown-manatee.sh
        container: qc.doc_nerdy-red-mammoth
      github.com/rjdmartins/try_ibergrid2022_sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-firebrick-camel.sh
        container: qc.doc_trippy-grey-spitz
      github.com/rjdmartins/try_ibergrid2022_sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-tomato-cougar.sh
        container: qc.doc_randy-cinnamon-swan
  QC.Lic:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-teal-havanese.sh
        container: qc.lic_surly-carmine-devil
  QC.Sec:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-pumpkin-eleuth.sh
        container: qc.sec_baggy-puce-stoat
  QC.Sty:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cobalt-tarantula.sh
        container: qc.sty_bluesy-fuchsia-eagle
  QC.Ver:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-azure-frise.sh
        container: qc.ver_jumpy-buff-tarantula
timeout: 1800
