config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rjdmartins/try_ibergrid2022_sqaaas:
      branch: master
      repo: https://github.com/rjdmartins/try_ibergrid2022_sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-peach-yak.sh
        container: qc.acc_paltry-wheat-discus
  QC.Doc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-burgundy-weasel.sh
        container: qc.doc_crabby-denim-stoat
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-saffron-ostrich.sh
        container: qc.doc_woozy-azure-fousek
      github.com/rjdmartins/try_ibergrid2022_sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cerise-fox.sh
        container: qc.doc_frumpy-white-audemer
      github.com/rjdmartins/try_ibergrid2022_sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-bronze-antelope.sh
        container: qc.doc_messy-ultramarine-millipede
  QC.Lic:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-salmon-frigatebird.sh
        container: qc.lic_woozy-goldenrod-leopard
  QC.Met:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pink-urchin.sh
        container: qc.met_wimpy-denim-newfoundland
      github.com/rjdmartins/try_ibergrid2022_sqaaas validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-malachite-leopard.sh
        container: qc.met_fuzzy-mustard-pinscher
  QC.Sec:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-linen-dane.sh
        container: qc.sec_wiggy-lemon-wallaby
  QC.Sty:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-gold-catfish.sh
        container: qc.sty_trippy-persimmon-bird
      github.com/rjdmartins/try_ibergrid2022_sqaaas jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-magpie.sh
        container: qc.sty_lanky-platinum-audemer
  QC.Ver:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-pear-monkey.sh
        container: qc.ver_sleepy-ruby-vole
timeout: 1800
