config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rjdmartins/try_ibergrid2022_sqaaas:
      branch: master
      repo: https://github.com/rjdmartins/try_ibergrid2022_sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-celadon-lobster.sh
        container: qc.acc_tasty-grey-angelfish
  QC.Doc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aqua-cichlid.sh
        container: qc.doc_stinky-turquoise-newfoundland
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-lavender-frog.sh
        container: qc.doc_shaggy-champagne-bloodhound
      github.com/rjdmartins/try_ibergrid2022_sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-denim-beagle.sh
        container: qc.doc_queasy-goldenrod-squid
      github.com/rjdmartins/try_ibergrid2022_sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-chartreuse-devil.sh
        container: qc.doc_woolly-malachite-yak
  QC.Lic:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-charcoal-fly.sh
        container: qc.lic_gummy-peach-toad
  QC.Sec:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-azure-jaguar.sh
        container: qc.sec_beady-goldenrod-cow
  QC.Sty:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-wheat-stoat.sh
        container: qc.sty_cheeky-orchid-goat
  QC.Ver:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-periwinkle-sparrow.sh
        container: qc.ver_pasty-lavender-quokka
timeout: 1800
