config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rjdmartins/try_ibergrid2022_sqaaas:
      branch: master
      repo: https://github.com/rjdmartins/try_ibergrid2022_sqaaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-apricot-frigatebird.sh
        container: qc.acc_craggy-heliotrope-dachsbracke
  QC.Doc:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-green-akbash.sh
        container: qc.doc_whiny-amaranth-toad
      github.com/rjdmartins/try_ibergrid2022_sqaaas git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-scarlet-guppy.sh
        container: qc.doc_lousy-black-emu
      github.com/rjdmartins/try_ibergrid2022_sqaaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orchid-manatee.sh
        container: qc.doc_sloppy-white-guppy
      github.com/rjdmartins/try_ibergrid2022_sqaaas restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-indigo-oyster.sh
        container: qc.doc_hilly-red-capybara
  QC.Lic:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-aqua-salamander.sh
        container: qc.lic_nerdy-xanthic-seal
  QC.Sec:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-lime-impala.sh
        container: qc.sec_surly-cerise-baboon
  QC.Sty:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cream-audemer.sh
        container: qc.sty_crabby-orchid-mole
  QC.Ver:
    repos:
      github.com/rjdmartins/try_ibergrid2022_sqaaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-seashell-gerbil.sh
        container: qc.ver_squirrely-azure-gibbon
timeout: 1800
